version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CONNECTION_URI=mongodb://mongo
    depends_on:
      - mongo
    volumes:
      - ./cogs:/modmailbot/cogs:ro
      - ./core:/modmailbot/core:ro
      - ./plugins:/modmailbot/plugins:ro

  logviewer:
    image: kyb3rr/logviewer
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo
    ports:
      - 80:8000

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    ports:
      - 27019:27019

volumes:
  mongodb:
