name: Modmail Workflow

on: [push, pull_request]

jobs:
  code-style:

#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
#        python-version: [3.6, 3.7]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --system
    # - name: Bandit syntax check
    #   run: bandit -r . -b .bandit_baseline.json
    - name: Pylint
      run: pylint ./bot.py cogs/*.py core/*.py  --exit-zero -r y
      continue-on-error: true
    - name: Black
      run: |
        black . --diff --check
